{{- if .Values.flyteadmin.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: flyte-admin-secrets
  namespace: {{ template "flyte.namespace" . }}
type: Opaque
stringData:
{{- with .Values.flyteadmin.secrets -}}
{{ tpl (toYaml .) $ | nindent 2 }}
{{- end }}
{{- end }}
