{{- if .Values.workflow_scheduler.enabled}}
  {{- if eq .Values.workflow_scheduler.type "native" }}
---
  {{- if .Values.flytescheduler.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "flytescheduler.name" . }}
  namespace: {{ template "flyte.namespace" . }}
  labels: {{ include "flytescheduler.labels" . | nindent 4 }}
  {{- with .Values.flytescheduler.serviceAccount.annotations }}
  annotations: {{ tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
  {{- with .Values.flytescheduler.serviceAccount.imagePullSecrets }}
imagePullSecrets: {{ tpl (toYaml .) $ | nindent 2 }}
  {{- end }}
  {{- end }}

---
{{- end }}
{{- end }}
